version: '2'
services:
    mehanicar-app:
        image: mehanicar
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mehanicar-mysql:3306/mehanicar?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    mehanicar-mysql:
        extends:
            file: mysql.yml
            service: mehanicar-mysql
